name: Events Demo 1
on:                // we have to defined our even in a new indented line 
  pull_request:
    types: 
      - opened
  workflow_dispatch:   // manual trigger , a second event ,  even there is not event , still have to put the ":"
      
jobs:
  deploy:                         // job Deploy 
    runs-on: ubuntu-lategit add st
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."